"""Format agent results into a human-readable text dossier."""

from __future__ import annotations


def _fmt(value, fmt_str: str, fallback: str = "N/A") -> str:
    """Format *value* with *fmt_str*; return *fallback* if None/missing."""
    if value is None:
        return fallback
    try:
        return fmt_str.format(value)
    except (ValueError, TypeError):
        return fallback


def _fmt_pct(value, decimals: int = 1, fallback: str = "N/A") -> str:
    """Format as percentage."""
    if value is None:
        return fallback
    try:
        import math
        if math.isnan(value):
            return fallback
        return f"{value * 100:+.{decimals}f}%" if value != 0 else f"{value * 100:.{decimals}f}%"
    except (ValueError, TypeError):
        return fallback


def _fmt_pct_abs(value, decimals: int = 1, fallback: str = "N/A") -> str:
    """Format as percentage (absolute, no sign)."""
    if value is None:
        return fallback
    try:
        import math
        if math.isnan(value):
            return fallback
        return f"{value * 100:.{decimals}f}%"
    except (ValueError, TypeError):
        return fallback


def _format_ticker(t: dict, macro: dict) -> str:
    """Format a single ticker block."""
    kpis = t["kpis"]
    price = t["price"]
    sent = t["sentiment"]
    val = t["valuation"]
    score = t["score"]

    # Header
    rec = t["profile_recommendation"]
    ps = t["profile_score"]
    rank = score.get("rank_overall", "?")

    lines = [
        "",
        f"[TICKER] {t['ticker']} -- {t['company_name']} ({t['sector']})",
        "-" * 55,
        f"  RECOMMENDATION: {rec} | Score: {ps:.1f}/100 | Rank: #{rank}/10",
        "",
        "  KEY METRICS (2024)",
        f"    ROE: {_fmt_pct_abs(kpis.get('roe'))} | "
        f"Net Margin: {_fmt_pct_abs(kpis.get('net_margin'))} | "
        f"Revenue CAGR: {_fmt_pct_abs(kpis.get('revenue_cagr'))}",
        f"    P/L: {_fmt(val.get('pl'), '{:.1f}x')} | "
        f"P/VP: {_fmt(val.get('pvp'), '{:.1f}x')} | "
        f"EV/EBITDA: {_fmt(val.get('ev_ebitda'), '{:.1f}x')}",
        "",
        "  MARKET SIGNALS",
        f"    Price: R${_fmt(price.get('current_price'), '{:.2f}')} | "
        f"52w High: R${_fmt(price.get('price_52w_high'), '{:.2f}')} | "
        f"52w Low: R${_fmt(price.get('price_52w_low'), '{:.2f}')}",
        f"    Volatility: {_fmt_pct_abs(price.get('volatility_annualized'))} | "
        f"Momentum 12m: {_fmt_pct(price.get('momentum_12m'))} | "
        f"Max Drawdown: {_fmt_pct(price.get('max_drawdown'))}",
        "",
        "  MACRO CONTEXT",
        f"    Selic: {_fmt_pct_abs(macro.get('selic_current'))} | "
        f"IPCA 12m: {_fmt(macro.get('ipca_last_12m'), '{:.1f}%')} | "
        f"USD/BRL: {_fmt(macro.get('usdbrl_current'), '{:.2f}')}",
        "",
        "  SENTIMENT",
        f"    Textual Index: {_fmt(sent.get('textual_index'), '{:.0f}')}/100 "
        f"({sent.get('sentiment_label', 'N/A')})",
        f"    Top risks:     {', '.join(sent.get('top_negative_keywords', [])) or 'none detected'}",
        f"    Top positives: {', '.join(sent.get('top_positive_keywords', [])) or 'none detected'}",
        "",
        "  SCENARIOS (2025 outlook)",
        f"    Bull: {_fmt_pct(val.get('bull_upside'))} upside | "
        f"Base: {_fmt_pct(val.get('base_upside'))} | "
        f"Bear: {_fmt_pct(val.get('bear_upside'))}",
        "",
        "  RISK FLAGS",
    ]
    for flag in t["risk_flags"]:
        lines.append(f"    - {flag}")

    lines += [
        "",
        "  AI SIGNALS",
        f"    Cluster: {score.get('cluster_label', 'N/A')} | "
        f"Outperform Prob: {_fmt_pct_abs(score.get('outperform_probability'))}",
        f"    Profile-adjusted Score: {ps:.1f}/100",
        "-" * 55,
    ]
    return "\n".join(lines)


def format_dossier(results: dict) -> str:
    """Convert full agent results dict into a text dossier string."""
    meta = results["metadata"]
    macro = results["macro"]
    tickers = results["tickers"]

    header = [
        "=" * 55,
        f"  EQUITY RESEARCH DOSSIER -- {meta['date']}",
        f"  Profile: {meta['profile']} | Generated by AI Agent",
        "=" * 55,
    ]

    body_parts = [_format_ticker(t, macro) for t in tickers]

    # Summary table
    summary_lines = [
        "",
        "=" * 55,
        "  SUMMARY TABLE",
        "=" * 55,
        f"  {'Ticker':<8} {'Rec':<6} {'Score':>6} {'Rank':>5} {'Cluster':<10} {'Base Upside':>12}",
        "  " + "-" * 50,
    ]
    for t in sorted(tickers, key=lambda x: -x["profile_score"]):
        val = t["valuation"]
        score = t["score"]
        base_up = val.get("base_upside")
        base_str = _fmt_pct(base_up) if base_up is not None else "N/A"
        summary_lines.append(
            f"  {t['ticker']:<8} {t['profile_recommendation']:<6} "
            f"{t['profile_score']:>6.1f} "
            f"{'#' + str(score.get('rank_overall', '?')):>5} "
            f"{score.get('cluster_label', 'N/A'):<10} "
            f"{base_str:>12}"
        )
    summary_lines.append("=" * 55)

    return "\n".join(header + body_parts + summary_lines) + "\n"
